[package]
build = "build.rs"
description = "events for the fyber protocol"
name = "fyber-events"

authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
bench = false
crate-type = ["cdylib", "rlib"]
doc = true
doctest = false
test = true

[[test]]
name = "default"

[dependencies]
fyber-core = { workspace = true }
# data structures
bytes = { optional = true, workspace = true }
# error
thiserror = { workspace = true }
# serialization
serde = { optional = true, workspace = true }
serde_derive = { optional = true, workspace = true }
serde_json = { optional = true, workspace = true }
# macros and utilities
strum = { workspace = true }
# WebAssembly
wasm-bindgen = { optional = true, workspace = true }

# ********* [metadata] *********
[package.metadata.docs.rs]
all-features = false
features = ["full"]
rustc-args = ["--cfg", "docsrs" ]
version = "v{{version}}"

[package.metadata.release]
no-dev-version = true
tag-name = "{{version}}"

[features]
default = [
  "std",
]

full = [
  "default",
  "json",
  "serde",
]

# ********* [FF] Features *********
json = [
  "alloc",
  "serde_json",
  "fyber-core/json",
]

nightly = [
  "fyber-core/nightly",
]

# ********* [FF] Environments *********
std = [
  "alloc",
  "fyber-core/std",
  "bytes?/std",
  "serde?/std",
  "serde_json?/std",
  "strum/std",
  "thiserror/std",
]

wasi = [
  "alloc",
  "fyber-core/wasi",
]

wasm = [
  "alloc",
  "fyber-core/wasm",
  "wasm-bindgen",
]

# ********* [FF] Dependencies *********
alloc = [
  "fyber-core/alloc",
  "serde?/alloc",
  "serde_json?/alloc",
]

bytes = ["dep:bytes"]

serde = [
  "dep:serde",
  "dep:serde_derive",
  "bytes?/serde",
  "serde?/derive",
  "fyber-core/serde",
]

serde_json = [
  "dep:serde_json",
  "fyber-core/serde_json",
]

wasm-bindgen = [
  "dep:wasm-bindgen",
  "fyber-core/wasm-bindgen",
]