name: crates-io

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ published ]
  repository_dispatch:
    types: [ crates-io ]
  workflow_dispatch:

permissions: write-all

jobs:
  publish:
    env:
      CRATENAME: ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - 
        name: publish
        run: cargo publish --all-features -v -p ${{ github.event.repository.name }}
      - 
        name: cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          restore-keys: |
            ${{ runner.os }}-cargo-
            ${{ runner.os }}-
